package nz.ac.auckland.se281.ai;

import nz.ac.auckland.se281.strategy.AverageStrategy;
import nz.ac.auckland.se281.strategy.ProcessStrategy;
import nz.ac.auckland.se281.strategy.RandomStrategy;

public class MediumLevel implements Level {

  // medium level initially uses random strategy and then switches to average strategy
  private ProcessStrategy processStrategy = new ProcessStrategy(new RandomStrategy());
  private int count = 1;

  @Override
  public int getFingers() {
    // change strategy to average strategy after 3 rounds
    if (count > 3) {
      processStrategy.setStrategy(new AverageStrategy());
    }
    count++;
    return processStrategy.getFingers();
  }

  @Override
  // returns the sum generated by the strategy
  public int getSum(int num) {
    return processStrategy.getSum(num);
  }
}
